### ISSUE TITLE
Help needed for using MigrateR scripts

### ISSUE THREAD

**Issue by zaarakidwai** [dbspitz/migrateR#20]
Hi Mr. Spitz,

I have been trying to fit movement models on some secondary telemetry and trajectory data that I have received from an organization. The data looks a lot like what needs to be entered in the code. However, I am not able to change it's class to ltraj or POSIXct, nor do I have the previous codes to see how those trajectories were developed. I was wondering if you could look at my file and let me know how to work with this file. Do I need to create separate file for each year and then create lists and work with that? I really don't know how to proceed. My end goal is to plot the NSDs for the species. Sending you a part of the data to show you what I have. These are from attribute tables of shape files. I would really appreciate your help with this, I don't understand how to move forward at all. 

regards,
Zaara
[Telemetry_points.csv](https://github.com/dbspitz/migrateR/files/15424587/Telemetry_points.csv)
[Trajectory_test2.csv](https://github.com/dbspitz/migrateR/files/15424596/Trajectory_test2.csv)

**Comment by eldritchmayo** [comment]
Hello Zaara,

Just letting you know you probably won`t be getting your anwsers here. Mr. Spitz has not been acctive for some time as you can see from the issues. And MigrateR has subsequently not been updated and has some issues so you might not be able to do whatever it is you were attempting. If you just want to see the NSD graphs, you can do that with the "amt" package much easily. However, for that, as well as for MigrateR  and other packages you need coordinates - Latitude and Longitude.

I am not familiar with this wkt_geom format. But if your points are just coordinates in another format (634075.10679999738931656 238844.58240000158548355 is actually - lat(63.4075), long(23.8844) - this is in Finland), than you can just reformat them as a Long and Lat collumn with some work in R and that should work fine. Alternatively, if these are not the coordinates and just indicate the place of points in a seperate coordinate system then you could(?) see where they are in relation to each other somehow, but this would lack the scale and position of the points on earth, rendering them uselles. If you just want to see the NSD graphs you could somehow(?) assign random coordinates so the points are in the same positions relative to each other and then plot them, but that seems like too much work for too little results.

**Comment by zaarakidwai** [comment]
Thank you for your response. However, I can't find any NSD analysis with amt package. Moreover, my R is not even showing any document for amt in the software itself. Is there any resource material you could help me out with please? The only thing I do have regarding amt is this paper https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.4823
I would appreciate your help.

**Comment by eldritchmayo** [comment]
You can find all the necessary documentations here: https://cran.r-project.org/web/packages/amt/index.html

Specifically the reference manual and maybe some of the vignettes.

You can find most documentation by just googling the package (not through scholar) or through the Help window in R Studio. Just try "help(amt)"

There are also other packages in R that you can use. Just google "nsd in R".

The NSD function is simply called "nsd" in the amt package you just need to reformat your data frame to the specifications.

I do not mean to be rude, but you did install the package, did you? I am not sure how experienced you are with R.

If you have some additional questions I suggest you write to me directly at:  so we do not fill the comments with irrelevant discussions. I also suggest you close the issue since it does not relate to the package itself.
