### ISSUE TITLE
migrateR will not install on R 3.5.2

### ISSUE THREAD

**Issue by dhondorp** [dbspitz/migrateR#4]
Hello,

I'm trying to install migrateR, but the installation always fails and R reports that:

'migrateR_1.0.7.tar.gz’ is not available (for R version 3.5.2)'

I've tried both the manual install and installing directly from gitHub-- neither works.  

Help!

-Darryl

**Comment by dbspitz** [comment]
Hi Darryl,

Thanks for the email. What are you working on?

Hmmm: the first hurdle. Installation errors can be a bit tricky as they're
often system specific.
Devtools is usually the easier path to troubleshoot here. Can you try
running the following and then send me the output?

  sessionInfo()
  packageDescription("devtools")

Might take a little back-and-forth to pin this down. My guess is an issue
with updates within one of the package dependencies, but R can be full of
surprises!

Best,


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by dhondorp** [comment]
dHi Derek,

Thanks for the quick response.  I'm analyzing the behavior of acoustic-tagged lake sturgeon in lakes huron and erie (and their connecting waters).  Just curious about how NSD models might fit the telemetry data.  

Attached is the output from those two function calls.  Let me know if something jumps out at you.
[sessionInfo.docx](https://github.com/dbspitz/migrateR/files/3163575/sessionInfo.docx)

**Comment by dhondorp** [comment]
Hi Derek,

Thanks for the quick response. I'm analyzing the behavior of
acoustic-tagged lake sturgeon in lakes huron and erie (and their connecting
waters). Just curious about how NSD models might fit the telemetry data.

Attached is the output from those two function calls. Let me know if
something jumps out at you.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Darryl W. Hondorp
Research Fish Biologist
USGS--Great Lakes Science Center
1451 Green Road
Ann Arbor, MI  48105
Office:  (734) 214-7241
Cell:  (734) 545-6258
Fax:  (734) 994-8780
Email: dhondorp@usgs.gov
USGS Professional Page: https://profile.usgs.gov/dhondorp
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dbspitz** [comment]
Has Spring reached Ann Arbor? Really curious to hear more about application
of NSD models to aquatic species. Once you get the packages working you'll
have to let me know what you think. I've been in touch with a couple
researchers in FL who have run into issues with increasing coastline
complexity; we'd discussed some possible solutions but ultimately issue
appeared to be unusual/infrequent.

Appreciate the code, but unfortunately nothing jumps out at me as obvious
so far. Is there any other information you can give me on the errors you're
seeing--e.g., any warnings, etc. before the 'not available' message or is
that the only output you're seeing?

If there's any more output leading up to the instillation failure, sending
me that code could be helpful. Otherwise, the only other obvious suggestion
for the moment would be the good ol' turn it off and on again 'trick':
close R, open with a fresh workspace, reinstall 'devtools', attempt the
instillation and see if you trigger the same error. A more aggressive form
of this could include reopening R to a fresh workspace and running through
'update.packages()'. If the issue is indeed with package versioning, these
approaches have a good chance of solving the problem.

I'm in meetings most of the rest of the day, but can take another look at
the code you sent tomorrow a.m. In the meantime, let me know if you run
into any other clues or hunches about the hang up. Unfortunately these
sorts of delays are sometimes the price of doing business in R, but we'll
get this figured out.

Good luck and keep me posted!


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by dhondorp** [comment]
Hey Derek,

Yes, we're into spring here.  Has been really wet, though.

Thanks for looking at the output.  I'll try a set another set of
installations after closing and restarting R and let you know what I find.


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Darryl W. Hondorp
Research Fish Biologist
USGS--Great Lakes Science Center
1451 Green Road
Ann Arbor, MI  48105
Office:  (734) 214-7241
Cell:  (734) 545-6258
Fax:  (734) 994-8780
Email: dhondorp@usgs.gov
USGS Professional Page: https://profile.usgs.gov/dhondorp
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dbspitz** [comment]
Hi Darryl,

Any updates? Would be interested in any added info. Hope you've had better
luck getting the package installed.

Best,


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by SimonePirrello** [comment]
Hi Derek, 
I reopen this discussion as I am running in the same issue of Darryl, as I am trying to install migrateR version 1.0.9 on R version 3.5.3 but it doesn't work.
All my R packages are updated and the version of devtools is 2.2.1

I ran the following code:
install_github("dbspitz/migrateR/migrateR", build_vignettes = T)
also tried with (...build_vignettes = F) but returns the following error:

Downloading GitHub repo dbspitz/migrateR@master
✓  checking for file ‘/private/var/folders/5y/0msbszcj3rx4t9pnptq9bjyh0000gq/T/RtmpDBm4DP/remotes23cc33bc760d/dbspitz-migrateR-6e5c413/migrateR/DESCRIPTION’ ...
─  preparing ‘migrateR’:
✓  checking DESCRIPTION meta-information
─  installing the package to build vignettes
✓  creating vignettes (11.1s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘migrateR_1.0.9.tar.gz’

Errore: Failed to install 'migrateR' from GitHub:
(contertito da avviso) incomplete final line found on '/Users/pirrello/.Rprofile'

Please, can you help me out with this issue?
Best,
Simone

**Comment by dbspitz** [comment]
Hi Simone,

Thanks for the email. Appreciate your including output. I wasn't able to
recreate the error, which makes tracking the problem down a bit tricky.
Here's my best guess, with links to stackoverflow:

The error looks like it may be a response to your .Rprofile, rather than
the package code. This error is typically caused if the last line of A file
is missing a return.
<https://stackoverflow.com/questions/5990654/incomplete-final-line-warning-when-trying-to-read-a-csv-file-into-r>
If this is the issue you should be able to fix the problem by rerunning the
install after manually adding a return at the end of your .Rprofile (tips
on finding your .Rprofile here
<https://stackoverflow.com/questions/13735745/locate-the-rprofile-file-generating-default-options>).
Alternatively, if you haven't already, the manual install instructions
might be worth trying (i.e., downloading the tarball and installing from
source). Finally, you could also try installing an earlier version of the
package with, e.g.:
  devtools::install_github("dbspitz/migrateR/migrateR@Version 1.0.8",
build_vignettes = T)

Hopefully one of these approaches does the trick. If so, please let me
know. I'd also be very interested in any new error messages you encounter.
Happy to help more with troubleshooting, but without being able to recreate
the issue myself, I'll be depending on you for more info.

Keep me posted and good luck!


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by SimonePirrello** [comment]
Hey Derek,

it was really a trivial error...I have just added a return at the end of my .Rprofile and then the installation of your package worked smoothly.
Thank you for your help!

Best,
Simone
