### ISSUE TITLE
Force model fit?

### ISSUE THREAD

**Issue by briana-abrahms** [dbspitz/migrateR#7]
Hi Derek,

Great package, thanks for putting so much work into it! Would it be possible to build into mvmtClass a way to force a model type to be fit? For example, I want all my individuals to be fit to a mixmig model, but currently that doesn't appear for all individuals. 

It would also be fantastic if there could be a mixmig option for the elevation model; I've replaced elevation with latitude and it works well. I also like this better since it's not sensitive to starting point. Is this something you'd consider adding?

Thanks,
Briana

**Comment by dbspitz** [comment]
Thanks, Briana.

Glad you're playing with other gradients--cool hearing that latitude is
doing the trick for ya. What kind of critters are you working with?

When models fail to fit, it is almost always because of poor starting
estimates. (Generating guesses at appropriate starting values for each
parameter is the most complex thing migrateR does behind the scenes.) This
is why it's not possible to "force" e.g., a mixmig model to fit-- if a
model is missing it's because migrateR's best guess isn't good enough and
better manual inputs are needed. If you want these models fit for all
individuals, you'll have to play around with manually setting starting
values (and/or bounds) using the "pEst" function and the "p.est" argument
in "mvmtClass".

Right now expansion of migrateR is limited to work I'm directly involved
with (such are the vagaries of the paycheck...).
I'm certainly willing to consider adding a mixmig model for elevation (and,
for that matter, tweaking the code to make altering axis labels easier) and
have added these to my list of potential projects for the future.
Maintaining the package is a top priority, though. If you encounter any
problems I'm always appreciative of a heads up.

Thanks,


Derek Spitz
Postdoc, UCSC
Bishop, CA
(831) 737-3120
CityOfKitesAndCrows.com <http://cityofkitesandcrows.com>
Wilmers Lab <http://wildlife.ucsc.edu> // Wittmer Lab
<http://cms.victoria.ac.nz/sbs/research/ecology-biodiversity-research/ecology-and-conservation-biology>

**Comment by briana-abrahms** [comment]
Hi Derek,

Thanks so much for your thoughtful responses here. I've played around with the starting parameters, but it's not doing the trick. I'm working on whooping crane migrations and they perform really nice clean latitudinal migrations, but unfortunately for some birds the data cuts off partway through the year so it looks like it was a disperser. I'd love to tell it to assign it as a migrant or mixed migrant and still estimate the migration timings. I'll make do for now!

Best,
Briana
